// Data describing only what a player can see mid-combat, for Normal (base game) difficulty.
// Sourced from the official wiki (https://wiki.diceydungeons.com/) -- stats from its text, and
// card colors, icons and effect wording from each equipment's card image (see README).
//
// Equipment `color`: { header, body } hex values pixel-sampled from the wiki's card image, plus
// an optional `slot` fill color for cards whose die-slot is a solid countdown box.
//
// Equipment `size`: inventory footprint, 1 or 2. Also sets the card's shape: size 1 is a wide
// card, size 2 a tall one (same width), as in the card art.
//
// Equipment `requirement`:
//   null                            -> no requirement, die-slot renders empty
//   { type: "max", value: N }       -> die-slot renders hashed with "MAX N"
//   { type: "min", value: N }       -> die-slot renders hashed with "MIN N"
//   { type: "even" } / { type: "odd" } -> die-slot renders hashed with "EVEN" / "ODD"
//   { type: "countdown", value: N } -> equipment self-triggers after N turns rather than
//                                       taking a die; die-slot renders solid with just N
//
// Equipment `bonusDieFace`: a fixed number the game renders as an actual die face (pips)
// instead of a digit, shown next to the die-slot. null if the equipment has no such bonus.
//
// Equipment `effect`: an ordered list of tokens describing the effect text, worded as on the card:
//   { type: "text", text }         -> plain text
//   { type: "icon", icon, value }  -> a small glyph (references #icon-<icon> in the SVG sprite),
//                                     optionally followed by a fixed number. Status icons (and
//                                     their number) are tinted per icon, see equipment-card.css.
//   { type: "dieSlot" }            -> a mini empty die-slot standing in for "the placed die's value"
//   { type: "lineBreak" }          -> a line break the card itself has
//
// Equipment `upgrade`: what changes when the player upgrades this equipment, as a partial override
// merged over the entry above -- only the fields that actually change are listed, and `{}` means
// the upgrade changes nothing the card shows. Allowed keys are `size`, `requirement`,
// `bonusDieFace` and `effect` (same shapes as above); the name's "+" and the ribbon are the
// renderer's job, and the colors never change. Sourced from the "Upgraded Effect" / "Upgraded
// Requirements" / "Upgraded Size" rows of the wiki's equipment pages, but worded the way this card
// words things rather than the way the wiki's prose does -- and the wiki text is not complete, so
// check art-references/ wherever it covers the card (see README).

const EQUIPMENT = {
  broadsword: {
    name: "Broadsword",
    color: { header: "#fd5e6c", body: "#8e324a" },
    size: 2,
    requirement: null,
    bonusDieFace: 2,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " + 2 damage" },
    ],
    upgrade: {
      bonusDieFace: 3,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 3 damage" },
      ],
    },
  },
  smallShield: {
    name: "Small Shield",
    color: { header: "#ff9048", body: "#9e5738" },
    size: 1,
    requirement: { type: "max", value: 3 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Add " },
      { type: "icon", icon: "shield" },
      { type: "dieSlot" },
      { type: "text", text: " shield" },
    ],
    upgrade: {
      bonusDieFace: 1,
      effect: [
        { type: "text", text: "Add " },
        { type: "icon", icon: "shield" },
        { type: "dieSlot" },
        { type: "text", text: " + 1 shield" },
      ],
    },
  },
  shovel: {
    name: "Shovel",
    color: { header: "#ff9048", body: "#9e5738" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "weaken" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "on 6, inflict " },
      { type: "icon", icon: "weaken", value: 1 },
      { type: "text", text: " weaken" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "weaken" },
        { type: "dieSlot" },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "on even, inflict " },
        { type: "icon", icon: "weaken", value: 1 },
      ],
    },
  },
  fireball: {
    name: "Fireball",
    color: { header: "#fd5e6c", body: "#9a3a38" },
    size: 1,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "fire" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Deal " },
        { type: "icon", icon: "fire" },
        { type: "dieSlot" },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "Burn " },
        { type: "icon", icon: "fire", value: 2 },
        { type: "text", text: " dice" },
      ],
    },
  },
  magicMissile: {
    name: "Magic Missile",
    color: { header: "#cdb94b", body: "#936b2a" },
    size: 1,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 5 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 8 },
        { type: "text", text: " damage" },
      ],
    },
  },
  magicShield: {
    name: "Magic Shield",
    color: { header: "#ff9048", body: "#ad6c40" },
    size: 1,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Add " },
      { type: "icon", icon: "shield", value: 3 },
      { type: "text", text: " shield" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Add " },
        { type: "icon", icon: "shield", value: 4 },
        { type: "text", text: " shield" },
      ],
    },
  },
  rayGun: {
    name: "Ray Gun",
    color: { header: "#fd5e6c", body: "#972631" },
    size: 1,
    requirement: { type: "min", value: 3 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 3 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "(3 uses this turn)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 4 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "(3 uses this turn)", muted: true },
      ],
    },
  },
  rosewoodSpear: {
    name: "Rosewood Spear",
    color: { header: "#5da66f", body: "#457d46" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "gain " },
      { type: "icon", icon: "thorns", value: 2 },
      { type: "text", text: " thorns" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "gain " },
        { type: "icon", icon: "thorns", value: 3 },
        { type: "text", text: " thorns" },
      ],
    },
  },
  slimeBall: {
    name: "Slime Ball",
    color: { header: "#b496ec", body: "#685b9e" },
    size: 1,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Add " },
      { type: "icon", icon: "poison", value: 2 },
      { type: "text", text: " poison" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Add " },
        { type: "icon", icon: "poison", value: 3 },
        { type: "text", text: " poison" },
      ],
    },
  },
  plasmaCannon: {
    name: "Plasma Cannon",
    color: { header: "#fd5e6c", body: "#992733", slot: "#ac2c38" },
    size: 1,
    requirement: { type: "countdown", value: 20 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 10 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 15 },
    },
  },
  woofWoofWoof: {
    name: "Woof Woof Woof",
    color: { header: "#fd5e6c", body: "#a53d40", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 8 },
    bonusDieFace: null,
    effect: [{ type: "text", text: "Repeat next action" }],
    upgrade: {
      requirement: { type: "countdown", value: 4 },
    },
  },
  wolfPuppyBite: {
    name: "Wolf Puppy Bite",
    color: { header: "#cdb94b", body: "#b97c34" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 4 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 5 },
        { type: "text", text: " damage" },
      ],
    },
  },
  avalanche: {
    name: "Avalanche",
    color: { header: "#7b7b7b", body: "#444a59" },
    size: 1,
    requirement: { type: "min", value: 3 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 3 },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "reroll with lower value" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 4 },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "reroll with lower value" },
      ],
    },
  },
  battleAxe: {
    name: "Battle Axe",
    color: { header: "#cdb94b", body: "#9f7226" },
    size: 2,
    requirement: { type: "max", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "text", text: "2x" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
    ],
    upgrade: { size: 1 },
  },
  bearMaul: {
    name: "Bear Maul",
    color: { header: "#fd5e6c", body: "#8b2f47" },
    size: 2,
    requirement: null,
    bonusDieFace: 2,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " + 2 damage" },
    ],
    upgrade: {
      bonusDieFace: 4,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 4 damage" },
      ],
    },
  },
  bearPotion: {
    name: "Bear Potion",
    color: { header: "#5da66f", body: "#2a6f4d", slot: "#2e7f40" },
    size: 2,
    requirement: { type: "countdown", value: 8 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Transform into a bear," },
      { type: "lineBreak" },
      { type: "text", text: "recover " },
      { type: "icon", icon: "heal", value: 12 },
      { type: "text", text: " health" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 6 },
    },
  },
  beeSting: {
    name: "Bee Sting",
    color: { header: "#cdb94b", body: "#936929", slot: "#c0882f" },
    size: 1,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "shock", value: 4 },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "shock", value: 1 },
      { type: "text", text: " shock" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "shock", value: 6 },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "Inflict " },
        { type: "icon", icon: "shock", value: 1 },
        { type: "text", text: " shock" },
      ],
    },
  },
  beetleHeadbutt: {
    name: "Beetle Headbutt",
    color: { header: "#b496ec", body: "#554081", slot: "#6d4fa5" },
    size: 2,
    requirement: { type: "countdown", value: 12 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 5 },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "Lock " },
      { type: "icon", icon: "lock", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 8 },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "Lock " },
        { type: "icon", icon: "lock", value: 1 },
        { type: "text", text: " dice" },
      ],
    },
  },
  blight: {
    name: "Blight",
    color: { header: "#b496ec", body: "#685b9e", slot: "#6d4fa5" },
    size: 1,
    requirement: { type: "countdown", value: 24 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Double " },
      { type: "icon", icon: "poison" },
      { type: "text", text: " poison" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 18 },
    },
  },
  bloodSuck: {
    name: "Blood Suck",
    color: { header: "#fd5e6c", body: "#86252e" },
    size: 2,
    requirement: { type: "max", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Drain " },
      { type: "icon", icon: "drain" },
      { type: "dieSlot" },
      { type: "text", text: " health" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  burningLight: {
    name: "Burning Light",
    color: { header: "#fd5e6c", body: "#aa3439" },
    size: 1,
    requirement: { type: "min", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "fire" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  cactusShield: {
    name: "Cactus Shield",
    color: { header: "#5da66f", body: "#388454" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Add " },
      { type: "icon", icon: "thorns", value: 1 },
      { type: "text", text: " thorns" },
      { type: "lineBreak" },
      { type: "text", text: "(Reuseable)", muted: true },
    ],
    upgrade: {
      requirement: null,
    },
  },
  cactusSpear: {
    name: "Cactus Spear",
    color: { header: "#5da66f", body: "#388455" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "+" },
      { type: "icon", icon: "sword", value: 1 },
      { type: "text", text: " for each " },
      { type: "icon", icon: "thorns" },
      { type: "text", text: " thorn" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "+" },
        { type: "icon", icon: "sword", value: 2 },
        { type: "text", text: " for each " },
        { type: "icon", icon: "thorns" },
        { type: "text", text: " thorn" },
      ],
    },
  },
  camouflage: {
    name: "Camouflage",
    color: { header: "#b496ec", body: "#533e83", slot: "#6d4fa5" },
    size: 2,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Blind " },
      { type: "icon", icon: "blind", value: 2 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Blind " },
        { type: "icon", icon: "blind", value: 4 },
        { type: "text", text: " dice" },
      ],
    },
  },
  campfire: {
    name: "Campfire",
    color: { header: "#fd5e6c", body: "#8b2f47" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " dmg, burn a dice" },
      { type: "lineBreak" },
      { type: "text", text: "Add +" },
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " each use" },
    ],
    upgrade: {
      effect: [
        { type: "icon", icon: "fire", value: 1 },
        { type: "text", text: " dmg, burn two dice" },
        { type: "lineBreak" },
        { type: "text", text: "Add +" },
        { type: "icon", icon: "fire", value: 1 },
        { type: "text", text: " each use" },
      ],
    },
  },
  cannonFire: {
    name: "Cannon Fire",
    color: { header: "#fd5e6c", body: "#a5384d", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 8 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "fire", value: 6 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Deal " },
        { type: "icon", icon: "fire", value: 8 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "Burn " },
        { type: "icon", icon: "fire", value: 1 },
        { type: "text", text: " dice" },
      ],
    },
  },
  cardboardSword: {
    name: "Cardboard Sword",
    color: { header: "#fd5e6c", body: "#a6384d" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 9 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Lose " },
      { type: "icon", icon: "sword", value: 2 },
      { type: "text", text: " each use" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 9 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "Lose " },
        { type: "icon", icon: "sword", value: 1 },
        { type: "text", text: " each use" },
      ],
    },
  },
  cauldron: {
    name: "Cauldron",
    color: { header: "#b496ec", body: "#594588" },
    size: 1,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 1 },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "get a new dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 1 },
        { type: "text", text: " dmg, reroll dice" },
        { type: "lineBreak" },
        { type: "text", text: "(2 uses this turn)", muted: true },
      ],
    },
  },
  charge: {
    name: "Charge!",
    color: { header: "#ff9048", body: "#b05f25", slot: "#c56125" },
    size: 2,
    requirement: { type: "countdown", value: 12 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Bash with shield," },
      { type: "lineBreak" },
      { type: "text", text: "do " },
      { type: "icon", icon: "shield", value: 0 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 9 },
    },
  },
  chocolateCookie: {
    name: "Chocolate Cookie",
    color: { header: "#ff9048", body: "#ab5730", slot: "#c56125" },
    size: 1,
    requirement: { type: "countdown", value: 12 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Repeat next action" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 9 },
    },
  },
  claw: {
    name: "Claw",
    color: { header: "#b496ec", body: "#685fa1" },
    size: 1,
    requirement: { type: "max", value: 3 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "and add " },
      { type: "icon", icon: "poison", value: 1 },
      { type: "text", text: " poison" },
    ],
    upgrade: {
      requirement: { type: "max", value: 5 },
    },
  },
  crystallize: {
    name: "Crystallize",
    color: { header: "#7b7b7b", body: "#5a423e", slot: "#545353" },
    size: 2,
    requirement: { type: "countdown", value: 6 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Create a random" },
      { type: "lineBreak" },
      { type: "text", text: "crystal weapon" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Create a random" },
        { type: "lineBreak" },
        { type: "text", text: "upgraded crystal weapon" },
      ],
    },
  },
  darkShadow: {
    name: "Dark Shadow",
    color: { header: "#7b7b7b", body: "#59413e" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "add 2x random status" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  deepSeaHowl: {
    name: "Deep Sea Howl",
    color: { header: "#b496ec", body: "#56428a" },
    size: 2,
    requirement: { type: "exact", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Curse enemy" },
    ],
    upgrade: {
      requirement: { type: "even" },
    },
  },
  direWolfHowl: {
    name: "Dire Wolf Howl",
    color: { header: "#b496ec", body: "#685fa2" },
    size: 2,
    requirement: { type: "doubles" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Curse enemy" },
    ],
    // The upgrade swaps the doubles sockets for a countdown; with no `slot` color
    // sampled for it, the countdown box falls back to the card's body color.
    upgrade: {
      requirement: { type: "countdown", value: 10 },
    },
  },
  dustCloud: {
    name: "Dust Cloud",
    color: { header: "#b496ec", body: "#554081" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "on 6, blind " },
      { type: "icon", icon: "blind", value: 2 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "blind " },
        { type: "icon", icon: "blind", value: 2 },
        { type: "text", text: " dice" },
      ],
    },
  },
  earthquake: {
    name: "Earthquake",
    color: { header: "#ff9048", body: "#b86531", slot: "#c56125" },
    size: 2,
    requirement: { type: "countdown", value: 10 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Weaken " },
      { type: "icon", icon: "weaken", value: 3 },
      { type: "text", text: " equipment," },
      { type: "lineBreak" },
      { type: "text", text: "do " },
      { type: "icon", icon: "weaken", value: 6 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Weaken " },
        { type: "icon", icon: "weaken", value: 3 },
        { type: "text", text: " equipment," },
        { type: "lineBreak" },
        { type: "text", text: "do " },
        { type: "icon", icon: "weaken", value: 9 },
        { type: "text", text: " damage" },
      ],
    },
  },
  echoBlast: {
    name: "Echo Blast",
    color: { header: "#ff9048", body: "#ab6028" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "weaken" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "+" },
      { type: "icon", icon: "weaken", value: 2 },
      { type: "text", text: " weaken" },
    ],
    upgrade: {
      bonusDieFace: 1,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "weaken" },
        { type: "dieSlot" },
        { type: "text", text: " + 1 damage" },
        { type: "lineBreak" },
        { type: "text", text: "+" },
        { type: "icon", icon: "weaken", value: 2 },
        { type: "text", text: " weaken" },
      ],
    },
  },
  electricShock: {
    name: "Electric Shock",
    color: { header: "#cdb94b", body: "#9a712e" },
    size: 1,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "shock" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "+" },
      { type: "icon", icon: "shock", value: 1 },
      { type: "text", text: " shock" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  electromagnet: {
    name: "Electromagnet",
    color: { header: "#fd5e6c", body: "#862735", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 7 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 4 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Add +2 each use" },
    ],
    upgrade: {
      size: 1,
    },
  },
  fireBreath: {
    name: "Fire Breath",
    color: { header: "#fd5e6c", body: "#ab3931", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "fire", value: 4 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "fire", value: 6 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "Burn " },
        { type: "icon", icon: "fire", value: 1 },
        { type: "text", text: " dice" },
      ],
    },
  },
  firePotion: {
    name: "Fire Potion",
    color: { header: "#fd5e6c", body: "#a1454e", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 8 },
    bonusDieFace: null,
    effect: [
      { type: "icon", icon: "fire", value: 8 },
      { type: "text", text: " damage, burn all dice" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 6 },
    },
  },
  fists: {
    name: "Fists",
    color: { header: "#fd5e6c", body: "#99444e" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 3 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "(2 uses this turn)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 4 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "(2 uses this turn)", muted: true },
      ],
    },
  },
  flameSpell: {
    name: "Flame Spell",
    color: { header: "#fd5e6c", body: "#86252e" },
    size: 1,
    requirement: { type: "exact", value: 2 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "fire", value: 5 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 2 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Deal " },
        { type: "icon", icon: "fire", value: 6 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "Burn all dice" },
      ],
    },
  },
  flight: {
    name: "Flight",
    color: { header: "#cdb94b", body: "#936928" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Dodge next attack" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  foolsFire: {
    name: "Fool's Fire",
    color: { header: "#df7cc4", body: "#875685", slot: "#94447e" },
    size: 2,
    requirement: { type: "countdown", value: 12 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "vanish", value: "Vanish" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 6 },
    },
  },
  freezeSpell: {
    name: "Freeze Spell",
    color: { header: "#7bc8ff", body: "#38718f" },
    size: 1,
    requirement: { type: "exact", value: 1 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "ice", value: 5 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Freeze " },
      { type: "icon", icon: "ice", value: 2 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Deal " },
        { type: "icon", icon: "ice", value: 5 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "Freeze all dice" },
      ],
    },
  },
  glare: {
    name: "Glare",
    color: { header: "#cdb94b", body: "#ad7d3f" },
    size: 2,
    requirement: { type: "exact", value: 1 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Lock " },
      { type: "icon", icon: "lock", value: 1 },
      { type: "text", text: " dice" },
      { type: "lineBreak" },
      { type: "text", text: "(2 uses this turn)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Lock " },
        { type: "icon", icon: "lock", value: 1 },
        { type: "text", text: " dice" },
        { type: "lineBreak" },
        { type: "text", text: "(Reuseable)", muted: true },
      ],
    },
  },
  glue: {
    name: "Glue",
    color: { header: "#b496ec", body: "#7453a0" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Lock " },
      { type: "icon", icon: "lock", value: 1 },
      { type: "text", text: " dice" },
      { type: "lineBreak" },
      { type: "text", text: "(2 uses this turn)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Lock " },
        { type: "icon", icon: "lock", value: 1 },
        { type: "text", text: " dice" },
        { type: "lineBreak" },
        { type: "text", text: "(3 uses this turn)", muted: true },
      ],
    },
  },
  hallOfMirrors: {
    name: "Hall of Mirrors",
    color: { header: "#b496ec", body: "#554081" },
    size: 1,
    requirement: { type: "exact", value: 6 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "+1 dice this fight" },
    ],
    upgrade: {
      requirement: { type: "even" },
    },
  },
  hammer: {
    name: "Hammer",
    color: { header: "#cdb94b", body: "#a66c2a" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "shock" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "on 6, inflict " },
      { type: "icon", icon: "shock", value: 1 },
      { type: "text", text: " shock" },
    ],
    upgrade: {
      size: 1,
    },
  },
  headbutt: {
    name: "Headbutt",
    color: { header: "#b496ec", body: "#6f417f" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "(2 uses this turn)", muted: true },
    ],
    upgrade: {
      bonusDieFace: 1,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 1 damage" },
        { type: "lineBreak" },
        { type: "text", text: "(2 uses this turn)", muted: true },
      ],
    },
  },
  heatwave: {
    name: "Heatwave",
    color: { header: "#fd5e6c", body: "#99404b", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "fire", value: 3 },
      { type: "text", text: ", inflict " },
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " burn" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "fire", value: 4 },
        { type: "text", text: ", inflict " },
        { type: "icon", icon: "fire", value: 1 },
        { type: "text", text: " burn" },
        { type: "lineBreak" },
        { type: "text", text: "(once per battle)", muted: true },
      ],
    },
  },
  highNote: {
    name: "High Note",
    color: { header: "#ff9048", body: "#994d1f", slot: "#c56125" },
    size: 2,
    requirement: { type: "countdown", value: 20 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "weaken", value: 12 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "weaken", value: 12 },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "icon", icon: "weaken", value: "Weakens" },
        { type: "text", text: " enemy" },
      ],
    },
  },
  hurricane: {
    name: "Hurricane",
    color: { header: "#b496ec", body: "#68548a", slot: "#6d4fa5" },
    size: 2,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 3 },
      { type: "text", text: ", lock " },
      { type: "icon", icon: "lock", value: 1 },
      { type: "text", text: " dice" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 4 },
        { type: "text", text: ", lock " },
        { type: "icon", icon: "lock", value: 1 },
        { type: "text", text: " dice" },
        { type: "lineBreak" },
        { type: "text", text: "(once per battle)", muted: true },
      ],
    },
  },
  iceAge: {
    name: "Ice Age",
    color: { header: "#7bc8ff", body: "#4282a6" },
    size: 2,
    requirement: [{ type: "exact", value: 1 }, { type: "exact", value: 1 }],
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Freeze all dice" },
    ],
    upgrade: {
      requirement: { type: "doubles" },
    },
  },
  iceShard: {
    name: "Ice Shard",
    color: { header: "#7bc8ff", body: "#4b86a7" },
    size: 1,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "ice" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "Freeze " },
      { type: "icon", icon: "ice", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  infliction: {
    name: "Infliction",
    color: { header: "#fd5e6c", body: "#ab3931" },
    size: 1,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 3 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 4 },
        { type: "text", text: " damage" },
      ],
    },
  },
  inkSplat: {
    name: "Ink Splat",
    color: { header: "#b496ec", body: "#685b9e" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Blind " },
      { type: "icon", icon: "blind", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Blind " },
        { type: "icon", icon: "blind", value: 1 },
        { type: "text", text: " dice" },
        { type: "lineBreak" },
        { type: "text", text: "(Reuseable)", muted: true },
      ],
    },
  },
  keyblade: {
    name: "Keyblade",
    color: { header: "#fd5e6c", body: "#902d32" },
    size: 1,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 3 },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "return the dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 4 },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "return the dice" },
      ],
    },
  },
  lament: {
    name: "Lament",
    color: { header: "#7bc8ff", body: "#395c6a" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "ice" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "on 6, inflict " },
      { type: "icon", icon: "ice", value: 1 },
      { type: "text", text: " freeze" },
    ],
    upgrade: {
      bonusDieFace: 1,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "ice" },
        { type: "dieSlot" },
        { type: "text", text: " + 1 damage," },
        { type: "lineBreak" },
        { type: "text", text: "on 6, inflict " },
        { type: "icon", icon: "ice", value: 1 },
        { type: "text", text: " freeze" },
      ],
    },
  },
  lock1: {
    name: "Lock 1",
    color: { header: "#7b7b7b", body: "#3d3f43" },
    size: 1,
    requirement: { type: "exact", value: 1 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Unlocks Keyblade," },
      { type: "lineBreak" },
      { type: "text", text: "return the dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Unlocks Keyblade+," },
        { type: "lineBreak" },
        { type: "text", text: "return the dice" },
      ],
    },
  },
  lock2: {
    name: "Lock 2",
    color: { header: "#7b7b7b", body: "#3d3f43" },
    size: 1,
    requirement: { type: "exact", value: 2 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Unlocks Keyblade," },
      { type: "lineBreak" },
      { type: "text", text: "return the dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Unlocks Keyblade+," },
        { type: "lineBreak" },
        { type: "text", text: "return the dice" },
      ],
    },
  },
  lock3: {
    name: "Lock 3",
    color: { header: "#7b7b7b", body: "#3d3f43" },
    size: 1,
    requirement: { type: "exact", value: 3 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Unlocks Keyblade," },
      { type: "lineBreak" },
      { type: "text", text: "return the dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Unlocks Keyblade+," },
        { type: "lineBreak" },
        { type: "text", text: "return the dice" },
      ],
    },
  },
  lock4: {
    name: "Lock 4",
    color: { header: "#7b7b7b", body: "#3d3f43" },
    size: 1,
    requirement: { type: "exact", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Unlocks Keyblade," },
      { type: "lineBreak" },
      { type: "text", text: "return the dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Unlocks Keyblade+," },
        { type: "lineBreak" },
        { type: "text", text: "return the dice" },
      ],
    },
  },
  lock5: {
    name: "Lock 5",
    color: { header: "#7b7b7b", body: "#3d3f43" },
    size: 1,
    requirement: { type: "exact", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Unlocks Keyblade," },
      { type: "lineBreak" },
      { type: "text", text: "return the dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Unlocks Keyblade+," },
        { type: "lineBreak" },
        { type: "text", text: "return the dice" },
      ],
    },
  },
  lock6: {
    name: "Lock 6",
    color: { header: "#7b7b7b", body: "#3d3f43" },
    size: 1,
    requirement: { type: "exact", value: 6 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Unlocks Keyblade," },
      { type: "lineBreak" },
      { type: "text", text: "return the dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Unlocks Keyblade+," },
        { type: "lineBreak" },
        { type: "text", text: "return the dice" },
      ],
    },
  },
  midnightCharm: {
    name: "Midnight Charm",
    color: { header: "#5da66f", body: "#388454", slot: "#2e7f40" },
    size: 1,
    requirement: { type: "countdown", value: 10 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Roll 2 sixes" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 5 },
    },
  },
  moodChange: {
    name: "Mood Change",
    color: { header: "#5da66f", body: "#347e51", slot: "#2e7f40" },
    size: 2,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Change the weather," },
      { type: "lineBreak" },
      { type: "text", text: "recover " },
      { type: "icon", icon: "heal", value: 3 },
      { type: "text", text: " health" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Change the weather," },
        { type: "lineBreak" },
        { type: "text", text: "recover " },
        { type: "icon", icon: "heal", value: 6 },
        { type: "text", text: " health" },
      ],
    },
  },
  mysteryBox: {
    name: "Mystery Box",
    color: { header: "#cdb94b", body: "#9f7226" },
    size: 1,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Very mysterious" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Contents upgraded" },
      ],
    },
  },
  nightmare: {
    name: "Nightmare",
    color: { header: "#b496ec", body: "#685fa2", slot: "#6d4fa5" },
    size: 2,
    requirement: { type: "countdown", value: 99 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 999 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 74 },
    },
  },
  overwhelm: {
    name: "Overwhelm",
    color: { header: "#fd5e6c", body: "#862533" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "icon", icon: "sword", value: 1 },
      { type: "text", text: " dmg, +" },
      { type: "icon", icon: "sword", value: 1 },
      { type: "text", text: " each use" },
      { type: "lineBreak" },
      { type: "text", text: "(2 uses this turn)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "icon", icon: "sword", value: 1 },
        { type: "text", text: " dmg, +" },
        { type: "icon", icon: "sword", value: 1 },
        { type: "text", text: " each use" },
        { type: "lineBreak" },
        { type: "text", text: "(3 uses this turn)", muted: true },
      ],
    },
  },
  peaShooter: {
    name: "Pea Shooter",
    color: { header: "#fd5e6c", body: "#842431", slot: "#ac2c38" },
    size: 1,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 2 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "(Reuseable)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 4 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "(Reuseable)", muted: true },
      ],
    },
  },
  pickpocket: {
    name: "Pickpocket",
    color: { header: "#5da66f", body: "#2f6c33" },
    size: 1,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Steals " },
      { type: "icon", icon: "gold", value: 1 },
      { type: "text", text: " gold" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Steals " },
        { type: "icon", icon: "gold", value: 2 },
        { type: "text", text: " gold" },
        { type: "lineBreak" },
        { type: "text", text: "(once per battle)", muted: true },
      ],
    },
  },
  pirateHook: {
    name: "Pirate Hook",
    color: { header: "#cdb94b", body: "#b97a32" },
    size: 2,
    requirement: { type: "max", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "on 4, you can re-use this" },
    ],
    upgrade: {
      requirement: null,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "on 5, you can re-use this" },
      ],
    },
  },
  pocketKnife: {
    name: "Pocket Knife",
    color: { header: "#fd5e6c", body: "#842330" },
    size: 1,
    requirement: { type: "max", value: 3 },
    bonusDieFace: 1,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " + 1 damage" },
      { type: "lineBreak" },
      { type: "text", text: "(3 uses this turn)", muted: true },
    ],
    upgrade: {
      bonusDieFace: 2,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 2 damage" },
        { type: "lineBreak" },
        { type: "text", text: "(Reuseable)", muted: true },
      ],
    },
  },
  poisonCloud: {
    name: "Poison Cloud",
    color: { header: "#b496ec", body: "#685fa1" },
    size: 1,
    requirement: { type: "max", value: 3 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "poison" },
      { type: "dieSlot" },
      { type: "text", text: " poison" },
    ],
    // The requirement caps the die at 3, so a flat 3 is the improvement.
    upgrade: {
      effect: [
        { type: "text", text: "Inflict " },
        { type: "icon", icon: "poison", value: 3 },
        { type: "text", text: " poison" },
      ],
    },
  },
  poisonSlingshot: {
    name: "Poison Slingshot",
    color: { header: "#b496ec", body: "#7453a0", slot: "#6d4fa5" },
    size: 1,
    requirement: { type: "countdown", value: 12 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Add " },
      { type: "icon", icon: "poison", value: 4 },
      { type: "text", text: " poison" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 9 },
    },
  },
  poisonSpell: {
    name: "Poison Spell",
    color: { header: "#b496ec", body: "#554081" },
    size: 1,
    requirement: { type: "exact", value: 3 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "poison", value: 4 },
      { type: "text", text: " poison" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Inflict " },
        { type: "icon", icon: "poison", value: 5 },
        { type: "text", text: " poison" },
      ],
    },
  },
  rat: {
    name: "Rat",
    color: { header: "#b496ec", body: "#544084", slot: "#6d4fa5" },
    size: 1,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "poison", value: 1 },
      { type: "text", text: " poison," },
      { type: "lineBreak" },
      { type: "text", text: "roll a new dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Inflict " },
        { type: "icon", icon: "poison", value: 1 },
        { type: "text", text: " poison," },
        { type: "lineBreak" },
        { type: "text", text: "roll a dice 3 or more" },
      ],
    },
  },
  rock: {
    name: "Rock",
    color: { header: "#fd5e6c", body: "#ab3831" },
    size: 1,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      bonusDieFace: 2,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 2 damage" },
        { type: "lineBreak" },
        { type: "text", text: "(once per battle)", muted: true },
      ],
    },
  },
  rottenCore: {
    name: "Rotten Core",
    color: { header: "#fd5e6c", body: "#ab3931", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 16 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Reduce health by half" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 12 },
    },
  },
  runAway: {
    name: "Run Away!",
    color: { header: "#cdb94b", body: "#9f7226", slot: "#c0882f" },
    size: 2,
    requirement: { type: "countdown", value: 20 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Run away!" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 15 },
    },
  },
  sadVerse: {
    name: "Sad Verse",
    color: { header: "#ff9048", body: "#be5f23" },
    size: 2,
    requirement: { type: "max", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "weaken" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "icon", icon: "weaken", value: "Weakens" },
      { type: "text", text: " enemy" },
    ],
    upgrade: {
      requirement: { type: "max", value: 5 },
    },
  },
  shootingStar: {
    name: "Shooting Star",
    color: { header: "#cdb94b", body: "#ba7f2a" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "inflict " },
      { type: "icon", icon: "confuse", value: "Confuse" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  shriek: {
    name: "Shriek",
    color: { header: "#b496ec", body: "#6c5287" },
    size: 2,
    requirement: { type: "exact", value: 2 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Curse enemy" },
    ],
    upgrade: {
      requirement: { type: "max", value: 2 },
    },
  },
  sinkhole: {
    name: "Sinkhole",
    color: { header: "#ff9048", body: "#b46d3f", slot: "#c56125" },
    size: 2,
    requirement: { type: "countdown", value: 12 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "weaken", value: 3 },
      { type: "text", text: " weaken" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Inflict " },
        { type: "icon", icon: "weaken", value: 4 },
        { type: "text", text: " weaken" },
      ],
    },
  },
  sixShooter: {
    name: "Six Shooter",
    color: { header: "#fd5e6c", body: "#99444f" },
    size: 2,
    requirement: { type: "exact", value: 6 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "(3 uses this turn)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "(6 uses this turn)", muted: true },
      ],
    },
  },
  smogCloud: {
    name: "Smog Cloud",
    color: { header: "#b496ec", body: "#5a4a9a", slot: "#6d4fa5" },
    size: 2,
    requirement: { type: "countdown", value: 15 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "poison", value: 3 },
      { type: "text", text: " poison" },
      { type: "lineBreak" },
      { type: "text", text: "and " },
      { type: "icon", icon: "blind", value: 3 },
      { type: "text", text: " blind" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Inflict " },
        { type: "icon", icon: "poison", value: 4 },
        { type: "text", text: " poison" },
        { type: "lineBreak" },
        { type: "text", text: "and " },
        { type: "icon", icon: "blind", value: 4 },
        { type: "text", text: " blind" },
      ],
    },
  },
  sneeze: {
    name: "Sneeze",
    color: { header: "#5da66f", body: "#457853" },
    size: 2,
    requirement: { type: "doubles" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Reduce the countdowns" },
      { type: "lineBreak" },
      { type: "text", text: "on all equipment by " },
      { type: "dieSlot" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Reduce the countdowns" },
        { type: "lineBreak" },
        { type: "text", text: "on all equipment to zero" },
      ],
    },
  },
  snowball: {
    name: "Snowball",
    color: { header: "#7bc8ff", body: "#315464" },
    size: 1,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "ice" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Freeze " },
      { type: "icon", icon: "ice", value: 1 },
      { type: "text", text: " dice" },
    ],
    // The die face is on the card art (art-references/snowball_upgrade.png); the wiki text has
    // only the "+ 1".
    upgrade: {
      bonusDieFace: 1,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "ice" },
        { type: "dieSlot" },
        { type: "text", text: " + 1 damage" },
        { type: "lineBreak" },
        { type: "text", text: "Freeze " },
        { type: "icon", icon: "ice", value: 1 },
        { type: "text", text: " dice" },
      ],
    },
  },
  snowstorm: {
    name: "Snowstorm",
    color: { header: "#7bc8ff", body: "#4282a6", slot: "#3a7ba8" },
    size: 2,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "ice", value: 3 },
      { type: "text", text: ", inflict " },
      { type: "icon", icon: "ice", value: 1 },
      { type: "text", text: " freeze" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "ice", value: 4 },
        { type: "text", text: ", inflict " },
        { type: "icon", icon: "ice", value: 1 },
        { type: "text", text: " freeze" },
        { type: "lineBreak" },
        { type: "text", text: "(once per battle)", muted: true },
      ],
    },
  },
  sonicWave: {
    name: "Sonic Wave",
    color: { header: "#ff9048", body: "#a3541e" },
    size: 1,
    requirement: { type: "max", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "weaken" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "icon", icon: "weaken", value: "Weakens" },
      { type: "text", text: " enemy" },
    ],
    upgrade: {
      requirement: { type: "max", value: 5 },
    },
  },
  spanner: {
    name: "Spanner",
    color: { header: "#5da66f", body: "#4a7937" },
    size: 1,
    requirement: [null, null],
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Combine dice" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Combine dice" },
        { type: "lineBreak" },
        { type: "text", text: "(3 uses this turn)", muted: true },
      ],
    },
  },
  spike: {
    name: "Spike",
    color: { header: "#fd5e6c", body: "#a5384d", slot: "#ac2c38" },
    size: 1,
    requirement: { type: "countdown", value: 6 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 3 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 4 },
    },
  },
  spikyPotion: {
    name: "Spiky Potion",
    color: { header: "#7b7b7b", body: "#585f5f", slot: "#545353" },
    size: 2,
    requirement: { type: "countdown", value: 8 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 8 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 6 },
    },
  },
  squawk: {
    name: "Squawk",
    color: { header: "#b496ec", body: "#685b9e" },
    size: 2,
    requirement: { type: "doubles" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Silence Enemy" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 2 },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "Silence Enemy" },
      ],
    },
  },
  teleportSpell: {
    name: "Teleport Spell",
    color: { header: "#cdb94b", body: "#9f7c39" },
    size: 1,
    requirement: { type: "exact", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Dodge next attack" },
    ],
    upgrade: {
      requirement: { type: "odd" },
    },
  },
  theAshes: {
    name: "The Ashes",
    color: { header: "#fd5e6c", body: "#862534" },
    size: 1,
    requirement: { type: "exact", value: 5 },
    bonusDieFace: 5,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "fire" },
      { type: "dieSlot" },
      { type: "text", text: " + 5 damage," },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 5 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      bonusDieFace: 6,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "fire" },
        { type: "dieSlot" },
        { type: "text", text: " + 6 damage," },
        { type: "lineBreak" },
        { type: "text", text: "Burn " },
        { type: "icon", icon: "fire", value: 5 },
        { type: "text", text: " dice" },
      ],
    },
  },
  theCold: {
    name: "The Cold",
    color: { header: "#7bc8ff", body: "#255178" },
    size: 1,
    requirement: { type: "exact", value: 4 },
    bonusDieFace: 4,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "ice" },
      { type: "dieSlot" },
      { type: "text", text: " + 4 damage," },
      { type: "lineBreak" },
      { type: "text", text: "Freeze " },
      { type: "icon", icon: "ice", value: 4 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      bonusDieFace: 5,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "ice" },
        { type: "dieSlot" },
        { type: "text", text: " + 5 damage," },
        { type: "lineBreak" },
        { type: "text", text: "Freeze " },
        { type: "icon", icon: "ice", value: 4 },
        { type: "text", text: " dice" },
      ],
    },
  },
  theCurse: {
    name: "The Curse",
    color: { header: "#b496ec", body: "#533e83" },
    size: 1,
    requirement: { type: "exact", value: 1 },
    bonusDieFace: 1,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " + 1 damage," },
      { type: "lineBreak" },
      { type: "text", text: "Inflict curse" },
    ],
    upgrade: {
      bonusDieFace: 4,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 4 damage," },
        { type: "lineBreak" },
        { type: "text", text: "Inflict curse" },
      ],
    },
  },
  theShadow: {
    name: "The Shadow",
    color: { header: "#7b7b7b", body: "#3d3e42" },
    size: 1,
    requirement: { type: "exact", value: 3 },
    bonusDieFace: 3,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " + 3 damage," },
      { type: "lineBreak" },
      { type: "text", text: "Blind " },
      { type: "icon", icon: "blind", value: 3 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      bonusDieFace: 5,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 5 damage," },
        { type: "lineBreak" },
        { type: "text", text: "Blind " },
        { type: "icon", icon: "blind", value: 3 },
        { type: "text", text: " dice" },
      ],
    },
  },
  theStorm: {
    name: "The Storm",
    color: { header: "#cdb94b", body: "#966c2e" },
    size: 1,
    requirement: { type: "exact", value: 6 },
    bonusDieFace: 6,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "shock" },
      { type: "dieSlot" },
      { type: "text", text: " + 6 damage," },
      { type: "lineBreak" },
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "shock", value: 6 },
      { type: "text", text: " shock" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "shock" },
        { type: "dieSlot" },
        { type: "text", text: " + 6 damage," },
        { type: "lineBreak" },
        { type: "text", text: "Shock " },
        { type: "icon", icon: "shock", value: 6 },
        { type: "text", text: " and silence" },
      ],
    },
  },
  theWind: {
    name: "The Wind",
    color: { header: "#fd5e6c", body: "#842330" },
    size: 1,
    requirement: { type: "exact", value: 2 },
    bonusDieFace: 2,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " + 2 damage," },
      { type: "lineBreak" },
      { type: "text", text: "Lock " },
      { type: "icon", icon: "lock", value: 2 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      bonusDieFace: 4,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 4 damage," },
        { type: "lineBreak" },
        { type: "text", text: "Lock " },
        { type: "icon", icon: "lock", value: 2 },
        { type: "text", text: " dice" },
      ],
    },
  },
  thunderSpell: {
    name: "Thunder Spell",
    color: { header: "#cdb94b", body: "#956b27" },
    size: 1,
    requirement: { type: "exact", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "shock", value: 5 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Shock " },
      { type: "icon", icon: "shock", value: 2 },
      { type: "text", text: " equipment" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Deal " },
        { type: "icon", icon: "shock", value: 5 },
        { type: "text", text: " damage" },
        { type: "lineBreak" },
        { type: "text", text: "Shock " },
        { type: "icon", icon: "shock", value: 3 },
        { type: "text", text: " equipment" },
      ],
    },
  },
  thunderStorm: {
    name: "Thunder Storm",
    color: { header: "#cdb94b", body: "#9f7226", slot: "#c0882f" },
    size: 2,
    requirement: { type: "countdown", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "shock", value: 3 },
      { type: "text", text: ", inflict " },
      { type: "icon", icon: "shock", value: 1 },
      { type: "text", text: " shock" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "shock", value: 4 },
        { type: "text", text: ", inflict " },
        { type: "icon", icon: "shock", value: 1 },
        { type: "text", text: " shock" },
        { type: "lineBreak" },
        { type: "text", text: "(once per battle)", muted: true },
      ],
    },
  },
  towerShield: {
    name: "Tower Shield",
    color: { header: "#ff9048", body: "#a3541e" },
    size: 2,
    requirement: { type: "max", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Add " },
      { type: "icon", icon: "shield" },
      { type: "dieSlot" },
      { type: "text", text: " shield" },
      { type: "lineBreak" },
      { type: "text", text: "(2 uses this turn)", muted: true },
    ],
    upgrade: {
      requirement: null,
    },
  },
  toxicPotion: {
    name: "Toxic Potion",
    color: { header: "#b496ec", body: "#685b9e", slot: "#6d4fa5" },
    size: 2,
    requirement: { type: "countdown", value: 8 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Inflict " },
      { type: "icon", icon: "poison", value: 5 },
      { type: "text", text: " poison" },
      { type: "lineBreak" },
      { type: "text", text: "(once per battle)", muted: true },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 6 },
    },
  },
  twoHandedSword: {
    name: "Two Handed Sword",
    color: { header: "#fd5e6c", body: "#8b2f47" },
    size: 2,
    requirement: [null, null],
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "on 12, lock " },
        { type: "icon", icon: "lock", value: 1 },
        { type: "text", text: " dice" },
      ],
    },
  },
  venusFlyTrap: {
    name: "Venus Fly Trap",
    color: { header: "#5da66f", body: "#447853" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "on 6, restore " },
      { type: "icon", icon: "heal", value: 2 },
      { type: "text", text: " health" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " damage," },
        { type: "lineBreak" },
        { type: "text", text: "on 6, restore " },
        { type: "icon", icon: "heal", value: 3 },
        { type: "text", text: " health" },
      ],
    },
  },
  wail: {
    name: "Wail",
    color: { header: "#b496ec", body: "#5f4780" },
    size: 2,
    requirement: { type: "exact", value: 5 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Silence Enemy" },
    ],
    upgrade: {
      requirement: { type: "min", value: 5 },
    },
  },
  wickerStaff: {
    name: "Wicker Staff",
    color: { header: "#fd5e6c", body: "#a6384d", slot: "#ac2c38" },
    size: 2,
    requirement: { type: "countdown", value: 12 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "fire", value: 9 },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 2 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      requirement: { type: "countdown", value: 9 },
    },
  },
  wormBite: {
    name: "Worm Bite",
    color: { header: "#ff9048", body: "#be5f23" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword", value: 1 },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword", value: 3 },
        { type: "text", text: " damage" },
      ],
    },
  },
  yoink: {
    name: "Yoink",
    color: { header: "#df7cc4", body: "#7e3e63" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Borrow equipment" },
      { type: "lineBreak" },
      { type: "text", text: "until next turn" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  airCrystal: {
    name: "Air Crystal",
    color: { header: "#cdb94b", body: "#9a7540" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "shock" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "+" },
      { type: "icon", icon: "shock", value: 1 },
      { type: "text", text: " shock" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  earthCrystal: {
    name: "Earth Crystal",
    color: { header: "#ff9048", body: "#ac6128" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "weaken" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "icon", icon: "weaken", value: "Weakens" },
      { type: "text", text: " enemy" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  fireCrystal: {
    name: "Fire Crystal",
    color: { header: "#fd5e6c", body: "#9a3a38" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Deal " },
      { type: "icon", icon: "fire" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
      { type: "lineBreak" },
      { type: "text", text: "Burn " },
      { type: "icon", icon: "fire", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  hollowCrystal: {
    name: "Hollow Crystal",
    color: { header: "#7b7b7b", body: "#49473f" },
    size: 2,
    requirement: null,
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "sword" },
      { type: "dieSlot" },
      { type: "text", text: " damage" },
    ],
    upgrade: {
      bonusDieFace: 2,
      effect: [
        { type: "text", text: "Do " },
        { type: "icon", icon: "sword" },
        { type: "dieSlot" },
        { type: "text", text: " + 2 damage" },
      ],
    },
  },
  iceCrystal: {
    name: "Ice Crystal",
    color: { header: "#7bc8ff", body: "#6072a5" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Do " },
      { type: "icon", icon: "ice" },
      { type: "dieSlot" },
      { type: "text", text: " damage," },
      { type: "lineBreak" },
      { type: "text", text: "Freeze " },
      { type: "icon", icon: "ice", value: 1 },
      { type: "text", text: " dice" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  lifeCrystal: {
    name: "Life Crystal",
    color: { header: "#5da66f", body: "#437651" },
    size: 2,
    requirement: { type: "max", value: 4 },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Recover " },
      { type: "icon", icon: "heal" },
      { type: "dieSlot" },
      { type: "text", text: " health" },
    ],
    upgrade: {
      requirement: { type: "max", value: 5 },
    },
  },
  powerCrystal: {
    name: "Power Crystal",
    color: { header: "#b496ec", body: "#633f7d" },
    size: 2,
    requirement: { type: "even" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Gain a random blessing" },
    ],
    upgrade: {
      requirement: null,
    },
  },
  smokeyCrystal: {
    name: "Smokey Crystal",
    color: { header: "#b496ec", body: "#68548a" },
    size: 2,
    requirement: { type: "odd" },
    bonusDieFace: null,
    effect: [
      { type: "text", text: "Curse enemy" },
    ],
    upgrade: {
      requirement: null,
    },
  },
};

// Enemies in the wiki's enemy-list order: by level, then bosses. The picker page groups them the
// same way (see enemyPickerGroups in render.js), keeping this order within each group.
//
// Enemy `level`: the wiki's level (1-5) for regular enemies. Bosses have `boss: true` instead.
//
// Enemy `equipment`: the equipment ids the enemy starts the fight with (repeat an id for copies).
// Optional extras, each rendered as its own headed section after the equipment:
//   equipmentNote: "..."                            -> a note under the Equipment heading, e.g.
//                                                      for an enemy with no equipment of its own
//   extraEquipment: [{ heading, equipment: [ids] }] -> cards the player may also see: a random
//                                                      loadout's possibilities, or cards gained
//                                                      mid-fight (e.g. "After Bear Potion")
const ENEMIES = {
  frog: {
    name: "Frog",
    level: 1,
    hp: 9,
    diceCount: 2,
    innateEffects: [],
    equipment: ["broadsword", "smallShield"],
  },
  gardener: {
    name: "Gardener",
    level: 1,
    hp: 12,
    diceCount: 2,
    innateEffects: [],
    equipment: ["shovel"],
  },
  hothead: {
    name: "Hothead",
    level: 1,
    hp: 14,
    diceCount: 2,
    innateEffects: ["Weak to ice"],
    equipment: ["fireball"],
  },
  magician: {
    name: "Magician",
    level: 1,
    hp: 9,
    diceCount: 1,
    innateEffects: [],
    equipment: ["magicMissile", "magicShield"],
  },
  robobot: {
    name: "Robobot",
    level: 1,
    hp: 12,
    diceCount: 3,
    innateEffects: [],
    equipment: ["rayGun"],
  },
  rose: {
    name: "Rose",
    level: 1,
    hp: 12,
    diceCount: 2,
    innateEffects: ["Weak to fire"],
    equipment: ["rosewoodSpear"],
  },
  slime: {
    name: "Slime",
    level: 1,
    hp: 14,
    diceCount: 2,
    innateEffects: ["Strong against poison"],
    equipment: ["slimeBall", "slimeBall"],
  },
  spaceMarine: {
    name: "Space Marine",
    level: 1,
    hp: 14,
    diceCount: 3,
    innateEffects: [],
    equipment: ["plasmaCannon"],
  },
  wolfPuppy: {
    name: "Wolf Puppy",
    level: 1,
    hp: 12,
    diceCount: 3,
    innateEffects: ["Strong against poison"],
    equipment: ["woofWoofWoof", "wolfPuppyBite"],
  },
  alchemist: {
    name: "Alchemist",
    level: 2,
    hp: 28,
    diceCount: 3,
    innateEffects: [],
    equipment: ["spikyPotion", "toxicPotion", "firePotion", "bearPotion"],
    extraEquipment: [
      {
        heading: "After Bear Potion",
        equipment: ["bearMaul", "bearMaul"],
      },
    ],
  },
  babySquid: {
    name: "Baby Squid",
    level: 2,
    hp: 26,
    diceCount: 2,
    innateEffects: [],
    equipment: ["inkSplat", "headbutt"],
  },
  dryad: {
    name: "Dryad",
    level: 2,
    hp: 26,
    diceCount: 3,
    innateEffects: ["Strong against poison"],
    equipment: ["poisonSlingshot", "venusFlyTrap"],
  },
  marshmallow: {
    name: "Marshmallow",
    level: 2,
    hp: 28,
    diceCount: 2,
    innateEffects: [],
    equipment: ["snowball", "fireball"],
  },
  mimic: {
    name: "Mimic",
    level: 2,
    hp: 28,
    diceCount: 3,
    innateEffects: [],
    equipment: ["mysteryBox"],
  },
  pirate: {
    name: "Pirate",
    level: 2,
    hp: 26,
    diceCount: 2,
    innateEffects: [],
    equipment: ["pirateHook", "cannonFire"],
  },
  sneezy: {
    name: "Sneezy",
    level: 2,
    hp: 24,
    diceCount: 3,
    innateEffects: [],
    equipment: ["sneeze", "spike", "spike", "spike", "spike"],
  },
  stereohead: {
    name: "Stereohead",
    level: 2,
    hp: 28,
    diceCount: 2,
    innateEffects: ["Weak to shock"],
    equipment: ["sonicWave", "sonicWave"],
  },
  stickyHands: {
    name: "Sticky Hands",
    level: 2,
    hp: 28,
    diceCount: 1,
    innateEffects: ["Goes first"],
    equipment: ["pickpocket", "runAway"],
  },
  wizard: {
    name: "Wizard",
    level: 2,
    hp: 28,
    diceCount: 1,
    innateEffects: [],
    equipment: ["freezeSpell", "flameSpell", "poisonSpell", "thunderSpell", "teleportSpell", "hallOfMirrors"],
  },
  bully: {
    name: "Bully",
    level: 3,
    hp: 34,
    diceCount: 2,
    innateEffects: [],
    equipment: ["rock", "rock", "rock", "rock", "fists"],
  },
  cactus: {
    name: "Cactus",
    level: 3,
    hp: 32,
    diceCount: 3,
    innateEffects: [],
    equipment: ["cactusSpear", "cactusShield"],
  },
  copycat: {
    name: "Copycat",
    level: 3,
    hp: 34,
    diceCount: 3,
    innateEffects: ["Copies your equipment"],
    equipment: [],
    equipmentNote: "None of its own: it uses copies of your equipment",
  },
  drainMonster: {
    name: "Drain Monster",
    level: 3,
    hp: 34,
    diceCount: 3,
    innateEffects: ["Strong against poison"],
    equipment: ["slimeBall", "slimeBall", "sinkhole"],
  },
  fireman: {
    name: "Fireman",
    level: 3,
    hp: 34,
    diceCount: 4,
    innateEffects: ["Weak to ice"],
    equipment: ["fireball", "fireball"],
  },
  handyman: {
    name: "Handyman",
    level: 3,
    hp: 32,
    diceCount: 3,
    innateEffects: [],
    equipment: ["hammer", "spanner", "peaShooter"],
  },
  hauntedJar: {
    name: "Haunted Jar",
    level: 3,
    hp: 34,
    diceCount: 4,
    innateEffects: ["Strong against poison"],
    equipment: ["poisonCloud", "blight"],
  },
  keymaster: {
    name: "Keymaster",
    level: 3,
    hp: 34,
    diceCount: 1,
    innateEffects: [],
    equipment: ["lock1", "lock2", "lock3", "lock4", "lock5", "lock6"],
    extraEquipment: [
      {
        heading: "Each Lock unlocks",
        equipment: ["keyblade"],
      },
    ],
  },
  sorceress: {
    name: "Sorceress",
    level: 3,
    hp: 34,
    diceCount: 2,
    innateEffects: [],
    equipment: ["cauldron", "infliction"],
    extraEquipment: [
      {
        heading: "Plus 2 random spells from",
        equipment: ["burningLight", "iceShard", "electricShock", "sonicWave"],
      },
    ],
  },
  vacuum: {
    name: "Vacuum",
    level: 3,
    hp: 30,
    diceCount: 3,
    innateEffects: [],
    equipment: ["dustCloud", "bloodSuck"],
  },
  yeti: {
    name: "Yeti",
    level: 3,
    hp: 34,
    diceCount: 4,
    innateEffects: ["Weak to fire"],
    equipment: ["iceShard", "iceShard", "iceAge"],
  },
  aurora: {
    name: "Aurora",
    level: 4,
    hp: 42,
    diceCount: 4,
    innateEffects: [],
    equipment: ["moodChange"],
    extraEquipment: [
      {
        heading: "Plus 3 copies of one of",
        equipment: ["hurricane", "thunderStorm", "heatwave", "snowstorm"],
      },
    ],
  },
  crystalina: {
    name: "Crystalina",
    level: 4,
    hp: 48,
    diceCount: 4,
    innateEffects: [],
    equipment: ["crystallize", "crystallize", "crystallize", "crystallize"],
    extraEquipment: [
      {
        heading: "Crystallize creates one of",
        equipment: ["airCrystal", "earthCrystal", "fireCrystal", "hollowCrystal", "iceCrystal", "lifeCrystal", "powerCrystal", "smokeyCrystal"],
      },
    ],
  },
  direWolf: {
    name: "Dire Wolf",
    level: 4,
    hp: 42,
    diceCount: 4,
    innateEffects: ["Strong against poison"],
    equipment: ["direWolfHowl", "claw", "claw"],
  },
  kraken: {
    name: "Kraken",
    level: 4,
    hp: 44,
    diceCount: 5,
    innateEffects: [],
    equipment: ["camouflage", "deepSeaHowl", "overwhelm"],
  },
  loudBird: {
    name: "Loud Bird",
    level: 4,
    hp: 44,
    diceCount: 4,
    innateEffects: [],
    equipment: ["squawk", "flight", "echoBlast"],
  },
  rhinoBeetle: {
    name: "Rhino Beetle",
    level: 4,
    hp: 46,
    diceCount: 3,
    innateEffects: [],
    equipment: ["battleAxe", "beetleHeadbutt"],
  },
  rottenApple: {
    name: "Rotten Apple",
    level: 4,
    hp: 44,
    diceCount: 3,
    innateEffects: [],
    equipment: ["rottenCore", "wormBite"],
  },
  snowman: {
    name: "Snowman",
    level: 4,
    hp: 44,
    diceCount: 4,
    innateEffects: ["Weak to fire"],
    equipment: ["snowball", "snowball", "snowball", "snowball"],
  },
  wickerMan: {
    name: "Wicker Man",
    level: 4,
    hp: 44,
    diceCount: 3,
    innateEffects: ["Weak to fire"],
    equipment: ["wickerStaff", "venusFlyTrap"],
  },
  wisp: {
    name: "Wisp",
    level: 4,
    hp: 42,
    diceCount: 4,
    innateEffects: ["Strong against fire"],
    equipment: ["foolsFire", "burningLight", "burningLight"],
  },
  banshee: {
    name: "Banshee",
    level: 5,
    hp: 50,
    diceCount: 4,
    innateEffects: [],
    equipment: ["wail", "lament", "lament", "shriek"],
  },
  bountyHunter: {
    name: "Bounty Hunter",
    level: 5,
    hp: 48,
    diceCount: 4,
    innateEffects: [],
    equipment: ["electromagnet", "yoink"],
  },
  cornelius: {
    name: "Cornelius",
    level: 5,
    hp: 100,
    diceCount: 0,
    innateEffects: ["+1 dice every turn"],
    equipment: ["nightmare"],
  },
  cowboy: {
    name: "Cowboy",
    level: 5,
    hp: 42,
    diceCount: 3,
    innateEffects: [],
    equipment: ["sixShooter", "midnightCharm"],
  },
  gargoyle: {
    name: "Gargoyle",
    level: 5,
    hp: 48,
    diceCount: 2,
    innateEffects: [],
    equipment: ["avalanche", "avalanche", "avalanche", "avalanche", "glare"],
  },
  paperKnight: {
    name: "Paper Knight",
    level: 5,
    hp: 48,
    diceCount: 3,
    innateEffects: ["Weak to fire"],
    equipment: ["cardboardSword", "glue"],
  },
  ratKing: {
    name: "Rat King",
    level: 5,
    hp: 42,
    diceCount: 3,
    innateEffects: ["Strong against poison"],
    equipment: ["rat", "rat", "rat", "rat", "rat", "rat"],
  },
  singer: {
    name: "Singer",
    level: 5,
    hp: 48,
    diceCount: 4,
    innateEffects: [],
    equipment: ["sadVerse", "sadVerse", "highNote"],
  },
  skeleton: {
    name: "Skeleton",
    level: 5,
    hp: 50,
    diceCount: 3,
    innateEffects: [],
    equipment: ["twoHandedSword", "shriek"],
  },
  warlock: {
    name: "Warlock",
    level: 5,
    hp: 48,
    diceCount: 3,
    innateEffects: [],
    equipment: ["shootingStar", "darkShadow"],
  },
  aoife: {
    name: "Aoife",
    boss: true,
    hp: 56,
    diceCount: 5,
    innateEffects: [],
    equipment: ["towerShield", "broadsword", "charge"],
  },
  audrey: {
    name: "Audrey",
    boss: true,
    hp: 74,
    diceCount: 4,
    innateEffects: [],
    equipment: ["headbutt", "earthquake"],
  },
  beatrice: {
    name: "Beatrice",
    boss: true,
    hp: 70,
    diceCount: 4,
    innateEffects: [],
    equipment: ["beeSting", "beeSting", "beeSting", "beeSting", "flight"],
  },
  buster: {
    name: "Buster",
    boss: true,
    hp: 68,
    diceCount: 4,
    innateEffects: ["Strong against fire"],
    equipment: ["fireBreath", "fireBreath", "fireBreath", "fireBreath"],
  },
  drake: {
    name: "Drake",
    boss: true,
    hp: 62,
    diceCount: 4,
    innateEffects: ["Must be killed with a wooden stake"],
    equipment: ["bloodSuck", "smogCloud"],
  },
  madison: {
    name: "Madison",
    boss: true,
    hp: 70,
    diceCount: 5,
    innateEffects: [],
    equipment: ["campfire", "pocketKnife", "chocolateCookie"],
  },
  scathach: {
    name: "Scathach",
    boss: true,
    hp: 70,
    diceCount: 1,
    innateEffects: ["Immune to lock and freeze"],
    equipment: ["theCurse", "theWind", "theShadow", "theCold", "theAshes", "theStorm"],
  },
};

// Lets the Node-side test suite read the same data; a no-op in the browser.
if (typeof module !== "undefined") module.exports = { EQUIPMENT, ENEMIES };
